### ISSUE TITLE
cannot download any model (certificate verify failed)

### ISSUE THREAD

**Issue by Lolologist** [nikitakit/self-attentive-parser#15]
>>> benepar.download('benepar_en')
[nltk_data] Error loading benepar_en: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed
[nltk_data]     (_ssl.c:847)>
False

Attempts to download the models as in the instructions fail due to the above. Any ideas?

**Comment by Lolologist** [comment]
Note that if I try to just make a parser for benepar_en, I get the following (asking me to try to download benepar_en.gz, which the instructions don't ask for, and neither works.):
 
>>> parser = benepar.Parser("benepar_en")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daniel/Repos/offsites/venv/lib/python3.6/site-packages/benepar/nltk_plugin.py", line 28, in __init__
    super(Parser, self).__init__(name, batch_size)
  File "/Users/daniel/Repos/offsites/venv/lib/python3.6/site-packages/benepar/base_parser.py", line 158, in __init__
    graph_def = tf.GraphDef.FromString(load_model(name))
  File "/Users/daniel/Repos/offsites/venv/lib/python3.6/site-packages/benepar/downloader.py", line 21, in load_model
    raise LookupError(arg)
LookupError: 
**********************************************************************
  Resource benepar_en.gz not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> benepar.download('benepar_en.gz')
  
  Attempted to load models/benepar_en.gz

  Searched in:
    - '/Users/daniel/nltk_data'
    - '/Users/daniel/Repos/offsites/venv/nltk_data'
    - '/Users/daniel/Repos/offsites/venv/share/nltk_data'
    - '/Users/daniel/Repos/offsites/venv/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************

**Comment by Lolologist** [comment]
Solved by following instructions here: https://stackoverflow.com/questions/41348621/ssl-error-downloading-nltk-data
