### ISSUE TITLE
Error when parsing the American Constitution with spacy

### ISSUE THREAD

**Issue by shlomihod** [nikitakit/self-attentive-parser#5]
I'm trying to run the parse using spacy on the American Constitution (https://pastebin.com/Ss2MWFVr) with this code:

```python
import spacy
from benepar.spacy_plugin import BeneparComponent

nlp = spacy.load('en')
nlp.add_pipe(BeneparComponent("benepar_en"))

nlp(american_constitution_text)
```
I'm getting an error - the error is different for using CPU or GPU. I've also tried longer text, and there is no problem. If I remove `nlp.add_pipe(BeneparComponent("benepar_en"))`, it works.

### CPU Error
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1321     try:
-> 1322       return fn(*args)
   1323     except errors.OpError as e:

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1306       return self._call_tf_sessionrun(
-> 1307           options, feed_dict, fetch_list, target_list, run_metadata)
   1308 

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1408           self._session, options, feed_dict, fetch_list, target_list,
-> 1409           run_metadata)
   1410     else:

InvalidArgumentError: indices[2590] = 29134 is not in [0, 19200)
	 [[Node: GatherV2_1 = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Tile, ToInt32, GatherV2_8/axis)]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-10-aeb678c45aba> in <module>()
----> 1 nlp_only_parsing(PROBLEMATIC_TEXT)

~/.local/lib/python3.5/site-packages/spacy/language.py in __call__(self, text, disable)
    350             if not hasattr(proc, '__call__'):
    351                 raise ValueError(Errors.E003.format(component=type(proc), name=name))
--> 352             doc = proc(doc)
    353             if doc is None:
    354                 raise ValueError(Errors.E005.format(name=name))

~/.local/lib/python3.5/site-packages/benepar/spacy_plugin.py in __call__(self, doc)
     75     def __call__(self, doc):
     76         constituent_data = PartialConstituentData()
---> 77         for parse_raw, sent in self._batched_parsed_raw(self._process_doc(doc)):
     78             # The optimized cython decoder implementation doesn't actually
     79             # generate trees, only scores and span indices. Indices follow a

~/.local/lib/python3.5/site-packages/benepar/base_parser.py in _batched_parsed_raw(self, sentence_data_pairs)
    220             batch_data.append(datum)
    221             if len(batch_sentences) >= self.batch_size:
--> 222                 for chart_np, datum in zip(self._make_charts(batch_sentences), batch_data):
    223                     yield chart_decoder.decode(chart_np), datum
    224                 batch_sentences = []

~/.local/lib/python3.5/site-packages/benepar/base_parser.py in _make_charts(self, sentences)
    203     def _make_charts(self, sentences):
    204         inp_val = self._charify(sentences)
--> 205         out_val = self._sess.run(self._charts, {self._chars: inp_val})
    206         for snum, sentence in enumerate(sentences):
    207             chart_size = len(sentence) + 1

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    898     try:
    899       result = self._run(None, fetches, feed_dict, options_ptr,
--> 900                          run_metadata_ptr)
    901       if run_metadata:
    902         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1133     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1134       results = self._do_run(handle, final_targets, final_fetches,
-> 1135                              feed_dict_tensor, options, run_metadata)
   1136     else:
   1137       results = []

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1314     if handle is None:
   1315       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1316                            run_metadata)
   1317     else:
   1318       return self._do_call(_prun_fn, handle, feeds, fetches)

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1333         except KeyError:
   1334           pass
-> 1335       raise type(e)(node_def, op, message)
   1336 
   1337   def _extend_graph(self):

InvalidArgumentError: indices[2590] = 29134 is not in [0, 19200)
	 [[Node: GatherV2_1 = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Tile, ToInt32, GatherV2_8/axis)]]

Caused by op 'GatherV2_1', defined at:
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.5/dist-packages/tornado/platform/asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1312, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 759, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 536, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-6f0432446d27>", line 6, in <module>
    nlp_only_parsing.add_pipe(BeneparComponent("benepar_en"))
  File "/home/users/shlohod/.local/lib/python3.5/site-packages/benepar/spacy_plugin.py", line 73, in __init__
    super(BeneparComponent, self).__init__(filename, batch_size)
  File "/home/users/shlohod/.local/lib/python3.5/site-packages/benepar/base_parser.py", line 163, in __init__
    tf.import_graph_def(graph_def, name='')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 513, in import_graph_def
    _ProcessNewOps(graph)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 303, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3540, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3540, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3428, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): indices[2590] = 29134 is not in [0, 19200)
	 [[Node: GatherV2_1 = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Tile, ToInt32, GatherV2_8/axis)]]
```

### GPU Error
```
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1321     try:
-> 1322       return fn(*args)
   1323     except errors.OpError as e:

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1306       return self._call_tf_sessionrun(
-> 1307           options, feed_dict, fetch_list, target_list, run_metadata)
   1308 

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1408           self._session, options, feed_dict, fetch_list, target_list,
-> 1409           run_metadata)
   1410     else:

ResourceExhaustedError: OOM when allocating tensor of shape [1024,16384] and type float
	 [[Node: ConstantFolding/bilm/RNN_0/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/kernel_enter = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [1024,16384] values: [0.0838829875 0.0388401747 0.173968613]...>, _device="/job:localhost/replica:0/task:0/device:GPU:0"](^bilm/RNN_0/RNN/MultiRNNCell/Cell1/rnn/while/lstm_cell/MatMul/Enter)]]

During handling of the above exception, another exception occurred:

ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-3-8f26748b155f> in <module>()
      5 nlp.add_pipe(BeneparComponent("benepar_en"))
      6 
----> 7 nlp(american)

~/.local/lib/python3.5/site-packages/spacy/language.py in __call__(self, text, disable)
    350             if not hasattr(proc, '__call__'):
    351                 raise ValueError(Errors.E003.format(component=type(proc), name=name))
--> 352             doc = proc(doc)
    353             if doc is None:
    354                 raise ValueError(Errors.E005.format(name=name))

~/.local/lib/python3.5/site-packages/benepar/spacy_plugin.py in __call__(self, doc)
     75     def __call__(self, doc):
     76         constituent_data = PartialConstituentData()
---> 77         for parse_raw, sent in self._batched_parsed_raw(self._process_doc(doc)):
     78             # The optimized cython decoder implementation doesn't actually
     79             # generate trees, only scores and span indices. Indices follow a

~/.local/lib/python3.5/site-packages/benepar/base_parser.py in _batched_parsed_raw(self, sentence_data_pairs)
    220             batch_data.append(datum)
    221             if len(batch_sentences) >= self.batch_size:
--> 222                 for chart_np, datum in zip(self._make_charts(batch_sentences), batch_data):
    223                     yield chart_decoder.decode(chart_np), datum
    224                 batch_sentences = []

~/.local/lib/python3.5/site-packages/benepar/base_parser.py in _make_charts(self, sentences)
    203     def _make_charts(self, sentences):
    204         inp_val = self._charify(sentences)
--> 205         out_val = self._sess.run(self._charts, {self._chars: inp_val})
    206         for snum, sentence in enumerate(sentences):
    207             chart_size = len(sentence) + 1

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    898     try:
    899       result = self._run(None, fetches, feed_dict, options_ptr,
--> 900                          run_metadata_ptr)
    901       if run_metadata:
    902         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1133     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1134       results = self._do_run(handle, final_targets, final_fetches,
-> 1135                              feed_dict_tensor, options, run_metadata)
   1136     else:
   1137       results = []

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1314     if handle is None:
   1315       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1316                            run_metadata)
   1317     else:
   1318       return self._do_call(_prun_fn, handle, feeds, fetches)

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1333         except KeyError:
   1334           pass
-> 1335       raise type(e)(node_def, op, message)
   1336 
   1337   def _extend_graph(self):

ResourceExhaustedError: OOM when allocating tensor of shape [1024,16384] and type float
	 [[Node: ConstantFolding/bilm/RNN_0/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/kernel_enter = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [1024,16384] values: [0.0838829875 0.0388401747 0.173968613]...>, _device="/job:localhost/replica:0/task:0/device:GPU:0"](^bilm/RNN_0/RNN/MultiRNNCell/Cell1/rnn/while/lstm_cell/MatMul/Enter)]]
```

**Comment by nikitakit** [comment]
Thanks for reporting!

The issue here is due to Section 8, which is a single (very long) sentence. The parser was not trained on sentences of this length, and there is a hard-coded limit of 300 words per sentence.

I'll work on updating the code to throw a more understandable error in this situation.

Unfortunately I don't see a straightforward way to relax the length restriction. The training sentences are much shorter (most are less than 40 words long), and the way word positions are represented in the parser has theoretical issues with generalizing to longer lengths. Moreover, the memory used by decoding algorithm scales as the square of the sentence length, which is why you are seeing OOM (out-of-memory) errors on GPU.

I'll think about what to do in these situations, but for now my recommendation would be to modify the text in some way to omit super-long sentences. For example, you can take turns deleting some of the "To ...;" lines and parsing the rest, and then combine everything to build a parse tree.

**Comment by shlomihod** [comment]
Thanks!

**Comment by nikitakit** [comment]
I'm closing this issue since I've added more understandable error messages when a sentence that is too long is given to the parser. Unfortunately there's no easy way to relax the length restrictions themselves, especially now that the recommended parser models use BERT (which has length limits of its own, for many of the same reasons).

**Comment by BramVanroy** [comment]
Just as an addition: it's always a good idea to set some limits on sentence lengths - often with a minimum as well as maximum length. (e.g. 3 - 150)
